"""UUIDv7 generation (RFC 9562).

Primary keys are generated by the *client*, so a create is idempotent: a retried
insert collides on the key instead of producing a duplicate row. v7 is used
rather than v4 because it is time-ordered, which keeps btree inserts localised
and gives a usable natural creation order without a second column.

Ordering is monotonic, not merely millisecond-granular: the 12-bit `rand_a`
field is used as a dedicated counter (RFC 9562 section 6.2, method 1) so that
ids minted within the same millisecond still sort by creation order. Without
this, a burst of writes -- exactly what draining an offline outbox looks like --
produces unordered keys.

Python 3.14 ships `uuid.uuid7()`, which is monotonic in the same way; this falls
back to a local implementation on 3.13 so the two behave identically.
"""

import secrets
import threading
import time
import uuid

_stdlib_uuid7 = getattr(uuid, "uuid7", None)

_lock = threading.Lock()
_last_ms = 0
_counter = 0

_COUNTER_MAX = 0xFFF  # rand_a is 12 bits
_COUNTER_SEED_BITS = 11  # seed in the low half, leaving headroom to increment


def _next_timestamp_and_counter() -> tuple[int, int]:
    global _last_ms, _counter

    with _lock:
        now_ms = time.time_ns() // 1_000_000

        if now_ms > _last_ms:
            _last_ms = now_ms
            _counter = secrets.randbits(_COUNTER_SEED_BITS)
        else:
            # Same millisecond, or the system clock went backwards (NTP step).
            # Advance the counter either way: ids must never regress, and a
            # backwards clock must not be able to mint a duplicate.
            _counter += 1
            if _counter > _COUNTER_MAX:
                # Counter exhausted within one millisecond. Borrow from the
                # future rather than emit an unordered id; the drift is at most
                # a millisecond and self-corrects on the next tick.
                _last_ms += 1
                _counter = secrets.randbits(_COUNTER_SEED_BITS)

        return _last_ms, _counter


def _uuid7() -> uuid.UUID:
    # 48 bits unix_ts_ms | 4 bits version | 12 bits counter
    # | 2 bits variant   | 62 bits random
    timestamp_ms, counter = _next_timestamp_and_counter()

    value = (timestamp_ms & 0xFFFFFFFFFFFF) << 80
    value |= 0x7 << 76
    value |= counter << 64
    value |= 0b10 << 62
    value |= secrets.randbits(62)
    return uuid.UUID(int=value)


uuid7 = _stdlib_uuid7 or _uuid7
