# Generated by Django 5.2.6 on 2026-09-09 10:19

import apps.core.uuids
import datetime
import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from apps.core.migration_ops import attach_row_version_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('component_mode', models.CharField(choices=[('NONE', 'No components'), ('ANY_OF', 'Any one component satisfies')], default='NONE', max_length=8)),
                ('requires_project', models.BooleanField(default=False)),
                ('allows_project', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(max_length=64)),
                ('elevation_m', models.SmallIntegerField(default=0)),
                ('calc_method', models.CharField(choices=[('MUSLIM_WORLD_LEAGUE', 'Muslim World League'), ('EGYPTIAN', 'Egyptian General Authority'), ('KARACHI', 'University of Islamic Sciences, Karachi'), ('UMM_AL_QURA', 'Umm al-Qura, Makkah'), ('DUBAI', 'Dubai'), ('MOON_SIGHTING_COMMITTEE', 'Moonsighting Committee'), ('NORTH_AMERICA', 'ISNA, North America'), ('KUWAIT', 'Kuwait'), ('QATAR', 'Qatar'), ('SINGAPORE', 'Singapore'), ('UOIF', 'Union des Organisations Islamiques de France')], default='UMM_AL_QURA', max_length=32)),
                ('madhab', models.CharField(choices=[('SHAFI', "Standard (Shafi'i, Maliki, Hanbali)"), ('HANAFI', 'Hanafi')], default='SHAFI', max_length=8)),
                ('high_latitude_rule', models.CharField(choices=[('MIDDLE_OF_THE_NIGHT', 'Middle of the night'), ('SEVENTH_OF_THE_NIGHT', 'Seventh of the night'), ('TWILIGHT_ANGLE', 'Twilight angle')], default='MIDDLE_OF_THE_NIGHT', max_length=24)),
                ('adjustments', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('singleton', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('day_rollover', models.TimeField(default=datetime.time(3, 0))),
                ('backfill_days', models.PositiveSmallIntegerField(default=7)),
                ('week_starts_on', models.SmallIntegerField(default=0)),
                ('prefetch_horizon_days', models.PositiveSmallIntegerField(default=35)),
            ],
            options={
                'verbose_name_plural': 'app settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', 1)), name='appsettings_singleton'), models.CheckConstraint(condition=models.Q(('week_starts_on__gte', 0), ('week_starts_on__lte', 6)), name='appsettings_week_start_in_range')],
            },
        ),
        migrations.CreateModel(
            name='HabitComponent',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=24)),
                ('label', models.CharField(max_length=40)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='habits.habit')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='HabitScheduleVersion',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('valid', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('frequency', models.CharField(choices=[('DAILY', 'Every eligible day'), ('TIMES_PER_WEEK', 'N times per week')], default='DAILY', max_length=16)),
                ('times_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('week_starts_on', models.SmallIntegerField(blank=True, null=True)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None)),
                ('rollover_mode', models.CharField(choices=[('INHERIT', 'Use the app-wide rollover'), ('FIXED', 'Fixed local time'), ('FAJR', 'Fajr to Fajr')], default='INHERIT', max_length=8)),
                ('rollover_time', models.TimeField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=140)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='habits.habit')),
            ],
            options={
                'ordering': ['habit', 'valid'],
            },
        ),
        migrations.CreateModel(
            name='HabitSlot',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=24)),
                ('label', models.CharField(max_length=40)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('anchor', models.CharField(choices=[('ALL_DAY', 'All day'), ('FIXED_TIME', 'Fixed local time'), ('PRAYER', 'Anchored to a prayer time')], default='ALL_DAY', max_length=12)),
                ('window_start_local', models.TimeField(blank=True, null=True)),
                ('window_end_local', models.TimeField(blank=True, null=True)),
                ('window_end_day_offset', models.SmallIntegerField(default=0)),
                ('prayer_key', models.CharField(blank=True, choices=[('FAJR', 'Fajr'), ('DHUHR', 'Dhuhr'), ('ASR', 'Asr'), ('MAGHRIB', 'Maghrib'), ('ISHA', 'Isha')], max_length=8, null=True)),
                ('window_end_rule', models.CharField(blank=True, choices=[('NEXT_PRAYER', 'Until the next prayer'), ('SUNRISE', 'Until sunrise'), ('ISLAMIC_MIDNIGHT', 'Until Islamic midnight'), ('FIXED_MINUTES', 'For a fixed number of minutes')], max_length=20, null=True)),
                ('window_end_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_unit', models.CharField(blank=True, max_length=16)),
                ('notify_offset_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('remind_before_end_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='habits.habitscheduleversion')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slot_key', models.CharField(max_length=24)),
                ('habit_day', models.DateField()),
                ('occurred_at', models.DateTimeField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ON_TIME', 'On time'), ('LATE', 'Late'), ('EARLY', 'Before the window opened'), ('UNKNOWN', 'Time not recorded')], default='UNKNOWN', max_length=8)),
                ('window_start_at', models.DateTimeField(blank=True, null=True)),
                ('window_end_at', models.DateTimeField(blank=True, null=True)),
                ('entry_mode', models.CharField(choices=[('LIVE', 'Logged as it happened'), ('BACKFILL', 'Filled in afterwards'), ('IMPORT', 'Imported')], default='LIVE', max_length=8)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='habits.habitcomponent')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='habits.habit')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habit_logs', to='tasks.project')),
                ('schedule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='habits.habitscheduleversion')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='habits.location')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationPeriod',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='habits.location')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerTimeDay',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('solar_date', models.DateField()),
                ('fajr_at', models.DateTimeField(null=True)),
                ('sunrise_at', models.DateTimeField(null=True)),
                ('dhuhr_at', models.DateTimeField(null=True)),
                ('asr_at', models.DateTimeField(null=True)),
                ('maghrib_at', models.DateTimeField(null=True)),
                ('isha_at', models.DateTimeField(null=True)),
                ('islamic_midnight_at', models.DateTimeField(null=True)),
                ('params_hash', models.CharField(max_length=64)),
                ('engine_version', models.CharField(max_length=32)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prayer_days', to='habits.location')),
            ],
            options={
                'ordering': ['solar_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='habitcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('habit', 'key'), name='component_key_unique_per_habit'),
        ),
        migrations.AddConstraint(
            model_name='habitscheduleversion',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('deleted_at__isnull', True)), expressions=[('habit', '='), ('valid', '&&')], name='schedule_version_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='habitscheduleversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frequency', 'TIMES_PER_WEEK'), _negated=True), ('times_per_week__gte', 1), _connector='OR'), name='times_per_week_required_when_weekly'),
        ),
        migrations.AddConstraint(
            model_name='habitscheduleversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rollover_mode', 'FIXED'), _negated=True), ('rollover_time__isnull', False), _connector='OR'), name='fixed_rollover_needs_a_time'),
        ),
        migrations.AddConstraint(
            model_name='habitslot',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('schedule_version', 'key'), name='slot_key_unique_per_version'),
        ),
        migrations.AddConstraint(
            model_name='habitslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anchor', 'FIXED_TIME'), _negated=True), models.Q(('window_start_local__isnull', False), ('window_end_local__isnull', False)), _connector='OR'), name='fixed_slot_needs_a_window'),
        ),
        migrations.AddConstraint(
            model_name='habitslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anchor', 'PRAYER'), _negated=True), models.Q(('prayer_key__isnull', False), ('window_end_rule__isnull', False)), _connector='OR'), name='prayer_slot_needs_key_and_end_rule'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'habit_day'], name='habits_habi_habit_i_1bf168_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit_day'], name='habits_habi_habit_d_159647_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'slot_key', 'habit_day'], name='habits_habi_habit_i_c338d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationperiod',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('deleted_at__isnull', True)), expressions=[('period', '&&')], name='locationperiod_no_overlap'),
        ),
        migrations.AddIndex(
            model_name='prayertimeday',
            index=models.Index(fields=['location', 'solar_date'], name='habits_pray_locatio_22b560_idx'),
        ),
        migrations.AddConstraint(
            model_name='prayertimeday',
            constraint=models.UniqueConstraint(fields=('location', 'solar_date'), name='prayertimeday_unique_per_location_date'),
        ),
        attach_row_version_trigger("habits_appsettings"),
        attach_row_version_trigger("habits_location"),
        attach_row_version_trigger("habits_locationperiod"),
        attach_row_version_trigger("habits_prayertimeday"),
        attach_row_version_trigger("habits_habit"),
        attach_row_version_trigger("habits_habitscheduleversion"),
        attach_row_version_trigger("habits_habitslot"),
        attach_row_version_trigger("habits_habitcomponent"),
        attach_row_version_trigger("habits_habitlog"),
    ]
