# Generated by Django 5.2.6 on 2026-09-09 10:13

import apps.core.uuids
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from apps.core.migration_ops import attach_row_version_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(blank=True, max_length=9)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuids._uuid7, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.BigIntegerField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('client_ts', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=0)),
                ('tag_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('due_is_all_day', models.BooleanField(default=True)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.project')),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_children', to='tasks.task')),
            ],
            options={
                'ordering': ['sort_order', '-priority', 'due_at'],
                'indexes': [models.Index(fields=['completed_at'], name='tasks_task_complet_b3d8de_idx'), models.Index(fields=['due_at'], name='tasks_task_due_at_59a3cb_idx'), models.Index(fields=['scheduled_for'], name='tasks_task_schedul_99e4e6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='task_is_not_its_own_parent')],
            },
        ),
        attach_row_version_trigger("tasks_project"),
        attach_row_version_trigger("tasks_tag"),
        attach_row_version_trigger("tasks_task"),
    ]
